version: "3"
services:
  warp:
    image: superng6/warp-proxy:latest
    ports:
      - 1080:1080
    restart: always
    environment:
      - "PROXY_PORT=1080"
      - "WARP_LICENSE="
      - "FAMILIES_MODE=off"
    volumes:
      - ./warp:/var/lib/cloudflare-warp
